version: "3.8"
services:
  auth-service:
    build: ./auth
    container_name: auth
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/users
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service

  inventory-service:
    build: ./inventory
    container_name: inventory
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27018/products
    ports:
      - "3001:3001"
